### ISSUE TITLE
hgx减速齿轮磨损情况咨询

### ISSUE THREAD

**Issue by liyiecho** [FZaii/FZburner#2]
大佬，不知道是不是模型问题还是买的hgx齿轮包有问题，我跟另一个群友都出现了减速齿轮的个别齿磨损情况，导致跳齿。不知道大佬有没有出现这种情况，望解答，谢谢。![Image_1721553355038.jpg](https://github.com/user-attachments/assets/92f3a337-fecc-4154-a47a-87670d40bfb4)

![Image_1721553351447.png](https://github.com/user-attachments/assets/7fe46e5f-1855-48c6-9f11-001002b6243d)

**Comment by FZaii** [comment]
特意拆了我的挤出机没有出现同样的磨损。 这里磨损是因为和电机齿咬合不到位？方便正面拍一下嘛？看看和电机齿的间隙

**Comment by liyiecho** [comment]
感谢大佬的回复，上面图片是群友的，没法提供正面的。不过我的磨损是这样。
![IMG_20240722_084331.png](https://github.com/user-attachments/assets/a7d43475-03a1-459f-a2cc-e4a970625b77)

![Screenshot_2024-07-22-08-47-31-934_com.miui.gallery-edit.jpg](https://github.com/user-attachments/assets/e5aded3d-6c6d-47a5-863f-f63a93da0f43)

![Screenshot_2024-07-22-08-42-50-359_com.miui.gallery-edit.jpg](https://github.com/user-attachments/assets/3de77c22-ddd0-4435-9e54-b6a844260e4d)

![Screenshot_2024-08-17-23-38-37-564_com.miui.gallery-edit.jpg](https://github.com/user-attachments/assets/64f6967f-82bb-419c-a630-fd45f7e5973a)

有几个齿磨损严重，猜测是因为加热片功率不够，温度不够高，导致挤出petg耗材阻力大，然后又因为打印头是petg耗材打印的，挤出电机发热量导致挤出机有点变软，最终导致pom减速轮有点偏心。再加上耗材齿轮的圆柱销硬度不够导致圆柱销被花键轴承磨出V槽，进一步磨损pom减速轮。
![Screenshot_2024-07-16-12-21-26-228_com.miui.gallery.png](https://github.com/user-attachments/assets/066d3bf7-77f0-4637-be6a-2a6ee3cea570)

![Screenshot_2024-07-16-12-21-41-015_com.miui.gallery.png](https://github.com/user-attachments/assets/c70e303b-59dc-4fe6-ba5d-b7d49bd151fb)

**Comment by FZaii** [comment]
和你的看法一样，应该是打印耗材问题，PETG太软了不适合。挤出机以及其他一些受力部件，一定要用ABS！！kexcelled家的ABS就梆硬但是贵，哪怕是我最近用Bing家那么软的ABS打印的这套挤出机，打印时间近500小时也没有发现可见的磨损。
另外轴承磨成这样是不是润滑不足，可以涂一些润滑脂、锂基脂，要粘度高一些的。

**Comment by liyiecho** [comment]
谢谢大佬解惑。圆柱销磨成这样是两颗树那套件里的硬度不够，用老虎钳夹着转一圈就能留下齿痕，现在已经换成轴承钢的了。
